name: otp_util
description: Implement TOPT and HOTP methods.
version: 1.0.0
homepage: https://github.com/dushiling
repository: https://github.com/dushiling/otp_util

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.2
  base32: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


